window.PLACES=[
  {
    "id": 1,
    "name": "Hamburg-Hammerbrook",
    "address": "Hamburg-Hammerbrook, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / photo urbaine",
    "quarter": "Hammerbrook",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du secteur · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 2,
    "name": "FABRIK Hamburg",
    "address": "Barnerstraße 36, 22765 Altona, Germany",
    "category": "Culture & musées",
    "detail": "Culture / lieu alternatif",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Fischmarkt%20Hamburg%20(14844005).jpeg?width=1200",
    "imageCredit": "Aperçu d’Altona · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 3,
    "name": "Kampnagel",
    "address": "Jarrestraße 20, 22303 Hamburg-Nord, Germany",
    "category": "Culture & musées",
    "detail": "Culture / architecture",
    "quarter": "Barmbek & City Nord",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Kampnagel%20(Hamburg).jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 4,
    "name": "Car Museum Prototyp",
    "address": "Shanghaiallee 7, 20457 Hamburg, Germany",
    "category": "Auto & insolite",
    "detail": "Auto / musée",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 5,
    "name": "Oldtimer Tankstelle",
    "address": "Billhorner Röhrendamm 4, 20539 Hamburg, Germany",
    "category": "Auto & insolite",
    "detail": "Auto / lieu insolite",
    "quarter": "Est du port",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B6hlbrandbr%C3%BCcke%20(Hamburg).jpg?width=1200",
    "imageCredit": "Aperçu du port · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 6,
    "name": "Isemarkt",
    "address": "Isestraße 1-73, 20144 Eimsbüttel, Germany",
    "category": "Marchés",
    "detail": "Marché / gastronomie",
    "quarter": "Schanze & Eimsbüttel",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ParkFiction%20in%20Hamburg-Sankt%20Pauli.jpg?width=1200",
    "imageCredit": "Aperçu du secteur · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 7,
    "name": "Fisch & So",
    "address": "Große Elbstraße 117, 22767 Altona, Germany",
    "category": "Manger & boire",
    "detail": "Gastronomie / poisson",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Fischmarkt%20Hamburg%20(14844005).jpeg?width=1200",
    "imageCredit": "Aperçu d’Altona · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 8,
    "name": "Atlantik Fisch & BistrOceaN",
    "address": "Große Elbstraße 139, 22767 Altona, Germany",
    "category": "Manger & boire",
    "detail": "Gastronomie / poisson",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Fischmarkt%20Hamburg%20(14844005).jpeg?width=1200",
    "imageCredit": "Aperçu d’Altona · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 9,
    "name": "Große Elbstraße",
    "address": "Große Elbstraße, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / port / photo",
    "quarter": "Altona & Fischmarkt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Fischmarkt%20Hamburg%20(14844005).jpeg?width=1200",
    "imageCredit": "Aperçu d’Altona · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 10,
    "name": "MUTTERLAND City",
    "address": "Poststraße 14-16, 20354 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Épicerie / produits locaux",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Aperçu du centre · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 11,
    "name": "Speicherstadt Coffee Roastery",
    "address": "Kehrwieder 5, 20457 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 12,
    "name": "Hobenköök Restaurant & Markthalle",
    "address": "Stockmeyerstraße 43, 20457 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Gastronomie / marché",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 13,
    "name": "Dat Backhus",
    "address": "Harburg-Arcaden Straße 39, 21073 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Boulangerie / snack",
    "quarter": "Harburg",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alte%20Harburger%20Elbbr%C3%BCcke%20(Hamburg-Harburg).jpg?width=1200",
    "imageCredit": "Aperçu de Harburg · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 14,
    "name": "Edeka Niemerszein on sand",
    "address": "Sand 31, 21073 Harburg, Germany",
    "category": "Manger & boire",
    "detail": "Courses / alimentation",
    "quarter": "Harburg",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alte%20Harburger%20Elbbr%C3%BCcke%20(Hamburg-Harburg).jpg?width=1200",
    "imageCredit": "Aperçu de Harburg · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 15,
    "name": "Wochenmarkt Harburg",
    "address": "Sand 37, 21073 Harburg, Germany",
    "category": "Marchés",
    "detail": "Marché / gastronomie",
    "quarter": "Harburg",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alte%20Harburger%20Elbbr%C3%BCcke%20(Hamburg-Harburg).jpg?width=1200",
    "imageCredit": "Aperçu de Harburg · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 16,
    "name": "Alte Harburger Elbbrücke",
    "address": "Alte Harburger Elbbrücke, 21079 Harburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / pont / photo",
    "quarter": "Harburg",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alte%20Harburger%20Elbbr%C3%BCcke%20(Hamburg-Harburg).jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 17,
    "name": "Binnenhafen",
    "address": "Harburger Schloßstraße 9, 21079 Harburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / port / photo",
    "quarter": "Harburg",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alte%20Harburger%20Elbbr%C3%BCcke%20(Hamburg-Harburg).jpg?width=1200",
    "imageCredit": "Aperçu de Harburg · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 18,
    "name": "Park Fiction",
    "address": "Schauermanns Park, Pinnasberg 27, 20359 Altona, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Parc / vue / photo",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ParkFiction%20in%20Hamburg-Sankt%20Pauli.jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 19,
    "name": "Pont de Köhlbrand",
    "address": "Köhlbrandbrücke, 21129 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / pont / photo",
    "quarter": "Port & Köhlbrand",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B6hlbrandbr%C3%BCcke%20(Hamburg).jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 20,
    "name": "City Nord",
    "address": "City Nord, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "Barmbek & City Nord",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Kampnagel%20(Hamburg).jpg?width=1200",
    "imageCredit": "Aperçu du nord · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 21,
    "name": "Oberhafen",
    "address": "Oberhafen, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 22,
    "name": "Ericusspitze",
    "address": "Ericusspitze, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 23,
    "name": "HafenCity Universität",
    "address": "20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / station / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 24,
    "name": "Université HafenCity Hambourg",
    "address": "Henning-Voscherau-Platz 1, 20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 25,
    "name": "Hamburg BUNKER",
    "address": "Feldstraße 66/5. Stock, 20359 Hamburg, Germany",
    "category": "Culture & musées",
    "detail": "Architecture / vue / culture",
    "quarter": "St. Pauli",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ParkFiction%20in%20Hamburg-Sankt%20Pauli.jpg?width=1200",
    "imageCredit": "Aperçu de St. Pauli · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 26,
    "name": "Alsterarkaden",
    "address": "Alsterarkaden 10, 20354 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / centre-ville",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Aperçu du centre · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 27,
    "name": "Miniatur Wunderland",
    "address": "Kehrwieder 2/Block D, 20457 Hamburg, Germany",
    "category": "Culture & musées",
    "detail": "Musée / attraction",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Miniatur%20Wunderland%20Hamburg.jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 28,
    "name": "Marshall Street Coffee",
    "address": "Schopenstehl 30, 20095 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Aperçu du centre · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 29,
    "name": "Playground Coffee St. Pauli",
    "address": "Detlev-Bremer-Straße 21, 20359 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "St. Pauli",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ParkFiction%20in%20Hamburg-Sankt%20Pauli.jpg?width=1200",
    "imageCredit": "Aperçu de St. Pauli · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 30,
    "name": "Nord Coast Coffee Roastery",
    "address": "Deichstraße 9, 20459 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Aperçu du centre · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 31,
    "name": "Public Coffee Roasters",
    "address": "Wexstraße 28, 20355 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Aperçu du centre · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 32,
    "name": "Public Coffee Roasters",
    "address": "Poststraße 12, 20354 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Aperçu du centre · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 33,
    "name": "m&k markt & kultur Veranststaltungs GmbH - Marktbüro",
    "address": "Wendenstraße 333, Innenhof 1. OG, 20537 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Marché / événement",
    "quarter": "Est du port",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B6hlbrandbr%C3%BCcke%20(Hamburg).jpg?width=1200",
    "imageCredit": "Aperçu du port · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 34,
    "name": "Elbtunnel-Bohrkopf (T.R.U.D.E. = Tief runter unter die Elbe)",
    "address": "22305 Hamburg-Nord, Germany",
    "category": "Architecture & photo",
    "detail": "Industriel / insolite / photo",
    "quarter": "Barmbek & City Nord",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Kampnagel%20(Hamburg).jpg?width=1200",
    "imageCredit": "Aperçu du nord · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 35,
    "name": "Kulturflohmarkt Museum der Arbeit",
    "address": "Wiesendamm 3, 22305 Hamburg-Nord, Germany",
    "category": "Marchés",
    "detail": "Marché aux puces",
    "quarter": "Barmbek & City Nord",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Kampnagel%20(Hamburg).jpg?width=1200",
    "imageCredit": "Aperçu du nord · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 36,
    "name": "Flohmarkt Flohschanze",
    "address": "Neuer Kamp 30, 20357 Altona, Germany",
    "category": "Marchés",
    "detail": "Marché aux puces",
    "quarter": "Schanze & Eimsbüttel",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ParkFiction%20in%20Hamburg-Sankt%20Pauli.jpg?width=1200",
    "imageCredit": "Aperçu du secteur · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 37,
    "name": "Reeperbahn",
    "address": "Reeperbahn, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / nightlife / photo",
    "quarter": "St. Pauli",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ParkFiction%20in%20Hamburg-Sankt%20Pauli.jpg?width=1200",
    "imageCredit": "Aperçu de St. Pauli · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 38,
    "name": "Heiligengeistfeld",
    "address": "Heiligengeistfeld 1, 20359 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Espace urbain / événement",
    "quarter": "St. Pauli",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ParkFiction%20in%20Hamburg-Sankt%20Pauli.jpg?width=1200",
    "imageCredit": "Aperçu de St. Pauli · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 39,
    "name": "Messe-Eingang Süd",
    "address": "20355 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Repère / salon",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Aperçu du centre · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 40,
    "name": "Ratsherrn Pilsener",
    "address": "Lagerstraße 30a, 20357 Altona, Germany",
    "category": "Manger & boire",
    "detail": "Brasserie / gastronomie",
    "quarter": "Schanze & Eimsbüttel",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ParkFiction%20in%20Hamburg-Sankt%20Pauli.jpg?width=1200",
    "imageCredit": "Aperçu du secteur · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 41,
    "name": "Fischmarkt Hamburg Altona",
    "address": "Fischmarkt 2, 22767 Altona, Germany",
    "category": "Marchés",
    "detail": "Marché / gastronomie",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Fischmarkt%20Hamburg%20(14844005).jpeg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 42,
    "name": "Altes Lotsenhaus",
    "address": "20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / port / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 43,
    "name": "Überseequartier",
    "address": "20457 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Architecture / quartier / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 44,
    "name": "Musical Boulevard Hamburg",
    "address": "Norderelbstraße 8, 20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / rive / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 45,
    "name": "Vieux tunnel sous l'Elbe",
    "address": "Bei den St. Pauli-Landungsbrücken, 20359 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / infrastructure / photo",
    "quarter": "St. Pauli",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alter%20Elbtunnel%202017%204.jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 46,
    "name": "Hard Rock Cafe Hamburg",
    "address": "Bei den St. Pauli-Landungsbrücken 5, 20359 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Bar / restaurant",
    "quarter": "St. Pauli",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/ParkFiction%20in%20Hamburg-Sankt%20Pauli.jpg?width=1200",
    "imageCredit": "Aperçu de St. Pauli · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 47,
    "name": "Hamburg Hauptbahnhof",
    "address": "Hachmannplatz 16, 20099 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Gare / architecture / photo",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg%20Hbf%20Wandelhalle.jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 48,
    "name": "Landzunge",
    "address": "Reginenstraße 13, 20539 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Vue / port / photo",
    "quarter": "Est du port",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B6hlbrandbr%C3%BCcke%20(Hamburg).jpg?width=1200",
    "imageCredit": "Aperçu du port · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 49,
    "name": "Elbbrücken",
    "address": "20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / station / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 50,
    "name": "Elbbrücken",
    "address": "20539 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / station / photo",
    "quarter": "Est du port",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/K%C3%B6hlbrandbr%C3%BCcke%20(Hamburg).jpg?width=1200",
    "imageCredit": "Aperçu du port · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 51,
    "name": "Lighthouse Zero",
    "address": "20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / art / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 52,
    "name": "Baakenhafen",
    "address": "20457 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 53,
    "name": "HafenCity",
    "address": "HafenCity, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 54,
    "name": "Chilehaus",
    "address": "Chilehaus, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "Centre",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 55,
    "name": "Fleetschlösschen by Daniel Wischer",
    "address": "Brooktorkai 17, 20457 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Restaurant / architecture",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 56,
    "name": "Oberhafenbrücke",
    "address": "Oberhafenbrücke, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / pont / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 57,
    "name": "Oberhafen-Kantine",
    "address": "Stockmeyerstraße 39, 20457 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Gastronomie / architecture",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 58,
    "name": "Chilehaus",
    "address": "Fischertwiete 2A, 20095 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 59,
    "name": "Speicherstadt",
    "address": "Speicherstadt, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 60,
    "name": "Unilever Haus",
    "address": "Unilever Haus, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg-Unilever-Haus.jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 61,
    "name": "Marco Polo Tower",
    "address": "Am Strandkai 3, 20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HamburgSpeicherstadt.jpg?width=1200",
    "imageCredit": "Aperçu du quartier · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 62,
    "name": "Dockland Office Building",
    "address": "Van-der-Smissen-Straße 9, 22767 Altona, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Fischmarkt%20Hamburg%20(14844005).jpeg?width=1200",
    "imageCredit": "Aperçu d’Altona · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 63,
    "name": "Elbphilharmonie Hamburg",
    "address": "Platz d. Deutschen Einheit 4, 20457 Hamburg, Germany",
    "category": "Culture & musées",
    "detail": "Architecture / culture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Elbphilharmonie,%20Hamburg.jpg?width=1200",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo"
  },
  {
    "id": 64,
    "name": "PHOXXI - Temporäres Haus der Photographie",
    "address": "Deichtorstraße 1-2, 20095 Hamburg, Germany",
    "category": "Culture & musées",
    "detail": "Photographie / musée",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1200",
    "imageCredit": "Aperçu du centre · Wikimedia Commons",
    "imageKind": "area"
  },
  {
    "id": 65,
    "name": "Lüneburger Str. 30",
    "address": "Lüneburger Str. 30, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Repère / Harburg",
    "quarter": "Harburg",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alte%20Harburger%20Elbbr%C3%BCcke%20(Hamburg-Harburg).jpg?width=1200",
    "imageCredit": "Aperçu de Harburg · Wikimedia Commons",
    "imageKind": "area"
  }
];
