window.PLACES=[
  {
    "id": 1,
    "name": "Hamburg-Hammerbrook",
    "address": "Hamburg-Hammerbrook, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / photo urbaine",
    "quarter": "Hammerbrook",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg%20Hammerbrook%20DS089n.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Hamburg_Hammerbrook_DS089n.jpg"
  },
  {
    "id": 2,
    "name": "FABRIK Hamburg",
    "address": "Barnerstraße 36, 22765 Altona, Germany",
    "category": "Culture & musées",
    "detail": "Culture / lieu alternatif",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Fabrik-Hamburg-Altona.JPG?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Fabrik-Hamburg-Altona.JPG"
  },
  {
    "id": 3,
    "name": "Kampnagel",
    "address": "Jarrestraße 20, 22303 Hamburg-Nord, Germany",
    "category": "Culture & musées",
    "detail": "Culture / architecture",
    "quarter": "Barmbek & City Nord",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Kampnagel%20(Hamburg).jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Kampnagel_(Hamburg).jpg"
  },
  {
    "id": 4,
    "name": "Car Museum Prototyp",
    "address": "Shanghaiallee 7, 20457 Hamburg, Germany",
    "category": "Auto & insolite",
    "detail": "Auto / musée",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/004%20Tourist%20attraction%20in%20Hamburg%20-%20Prototyp%20car%20prototype%20museum.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:004_Tourist_attraction_in_Hamburg_-_Prototyp_car_prototype_museum.jpg"
  },
  {
    "id": 5,
    "name": "Oldtimer Tankstelle",
    "address": "Billhorner Röhrendamm 4, 20539 Hamburg, Germany",
    "category": "Auto & insolite",
    "detail": "Auto / lieu insolite",
    "quarter": "Est du port",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Historie-%20und%20Oldtimer-Tankstelle%20Brandshof.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Historie-_und_Oldtimer-Tankstelle_Brandshof.jpg"
  },
  {
    "id": 6,
    "name": "Isemarkt",
    "address": "Isestraße 1-73, 20144 Eimsbüttel, Germany",
    "category": "Marchés",
    "detail": "Marché / gastronomie",
    "quarter": "Schanze & Eimsbüttel",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 7,
    "name": "Fisch & So",
    "address": "Große Elbstraße 117, 22767 Altona, Germany",
    "category": "Manger & boire",
    "detail": "Gastronomie / poisson",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 8,
    "name": "Atlantik Fisch & BistrOceaN",
    "address": "Große Elbstraße 139, 22767 Altona, Germany",
    "category": "Manger & boire",
    "detail": "Gastronomie / poisson",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 9,
    "name": "Große Elbstraße",
    "address": "Große Elbstraße, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / port / photo",
    "quarter": "Altona & Fischmarkt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Gro%C3%9Fe%20Elbstra%C3%9Fe%20(Hamburg-Altona-Altstadt).2.phb.ajb.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Gro%C3%9Fe_Elbstra%C3%9Fe_(Hamburg-Altona-Altstadt).2.phb.ajb.jpg"
  },
  {
    "id": 10,
    "name": "MUTTERLAND City",
    "address": "Poststraße 14-16, 20354 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Épicerie / produits locaux",
    "quarter": "Centre",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 11,
    "name": "Speicherstadt Coffee Roastery",
    "address": "Kehrwieder 5, 20457 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 12,
    "name": "Hobenköök Restaurant & Markthalle",
    "address": "Stockmeyerstraße 43, 20457 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Gastronomie / marché",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 13,
    "name": "Dat Backhus",
    "address": "Harburg-Arcaden Straße 39, 21073 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Boulangerie / snack",
    "quarter": "Harburg",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 14,
    "name": "Edeka Niemerszein on sand",
    "address": "Sand 31, 21073 Harburg, Germany",
    "category": "Manger & boire",
    "detail": "Courses / alimentation",
    "quarter": "Harburg",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 15,
    "name": "Wochenmarkt Harburg",
    "address": "Sand 37, 21073 Harburg, Germany",
    "category": "Marchés",
    "detail": "Marché / gastronomie",
    "quarter": "Harburg",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 16,
    "name": "Alte Harburger Elbbrücke",
    "address": "Alte Harburger Elbbrücke, 21079 Harburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / pont / photo",
    "quarter": "Harburg",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alte%20Harburger%20Elbbr%C3%BCcke%20(Hamburg-Harburg).jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Alte_Harburger_Elbbr%C3%BCcke_(Hamburg-Harburg).jpg"
  },
  {
    "id": 17,
    "name": "Binnenhafen",
    "address": "Harburger Schloßstraße 9, 21079 Harburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / port / photo",
    "quarter": "Harburg",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Harburger%20Binnenhafen%20(4).jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Harburger_Binnenhafen_(4).jpg"
  },
  {
    "id": 18,
    "name": "Park Fiction",
    "address": "Schauermanns Park, Pinnasberg 27, 20359 Altona, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Parc / vue / photo",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg%20-%20Park%20Fiction%20(7).jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Hamburg_-_Park_Fiction_(7).jpg"
  },
  {
    "id": 19,
    "name": "Pont de Köhlbrand",
    "address": "Köhlbrandbrücke, 21129 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / pont / photo",
    "quarter": "Port & Köhlbrand",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Koehlbrandbruecke.JPG?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Koehlbrandbruecke.JPG"
  },
  {
    "id": 20,
    "name": "City Nord",
    "address": "City Nord, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "Barmbek & City Nord",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/City%20nord%20exNixdorf%20und%20%C3%9Cberseering.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:City_nord_exNixdorf_und_%C3%9Cberseering.jpg"
  },
  {
    "id": 21,
    "name": "Oberhafen",
    "address": "Oberhafen, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/HH%20Hammerbrook%20Fruchthof.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:HH_Hammerbrook_Fruchthof.jpg"
  },
  {
    "id": 22,
    "name": "Ericusspitze",
    "address": "Ericusspitze, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Ericusspitze%20Hamburg.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Ericusspitze_Hamburg.jpg"
  },
  {
    "id": 23,
    "name": "HafenCity Universität",
    "address": "20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / station / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/U-Bahnhof%20HafenCity%20Universit%C3%A4t%20Bahnsteig%202.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:U-Bahnhof_HafenCity_Universit%C3%A4t_Bahnsteig_2.jpg"
  },
  {
    "id": 24,
    "name": "Université HafenCity Hambourg",
    "address": "Henning-Voscherau-Platz 1, 20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg%20-%20HafenCity%20Universit%C3%A4t%20Hamburg.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Hamburg_-_HafenCity_Universit%C3%A4t_Hamburg.jpg"
  },
  {
    "id": 25,
    "name": "Hamburg BUNKER",
    "address": "Feldstraße 66/5. Stock, 20359 Hamburg, Germany",
    "category": "Culture & musées",
    "detail": "Architecture / vue / culture",
    "quarter": "St. Pauli",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Bunker,%20Heiligeneistfeld%20Hamburg.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Bunker,_Heiligeneistfeld_Hamburg.jpg"
  },
  {
    "id": 26,
    "name": "Alsterarkaden",
    "address": "Alsterarkaden 10, 20354 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / centre-ville",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alsterarkaden%20in%20Hamburg-Altstadt.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Alsterarkaden_in_Hamburg-Altstadt.jpg"
  },
  {
    "id": 27,
    "name": "Miniatur Wunderland",
    "address": "Kehrwieder 2/Block D, 20457 Hamburg, Germany",
    "category": "Culture & musées",
    "detail": "Musée / attraction",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Miniatur%20Wunderland%20Hamburg.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Miniatur_Wunderland_Hamburg.jpg"
  },
  {
    "id": 28,
    "name": "Marshall Street Coffee",
    "address": "Schopenstehl 30, 20095 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "Centre",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 29,
    "name": "Playground Coffee St. Pauli",
    "address": "Detlev-Bremer-Straße 21, 20359 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "St. Pauli",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 30,
    "name": "Nord Coast Coffee Roastery",
    "address": "Deichstraße 9, 20459 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "Centre",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 31,
    "name": "Public Coffee Roasters",
    "address": "Wexstraße 28, 20355 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "Centre",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 32,
    "name": "Public Coffee Roasters",
    "address": "Poststraße 12, 20354 Hamburg, Germany",
    "category": "Cafés",
    "detail": "Café",
    "quarter": "Centre",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 33,
    "name": "m&k markt & kultur Veranststaltungs GmbH - Marktbüro",
    "address": "Wendenstraße 333, Innenhof 1. OG, 20537 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Marché / événement",
    "quarter": "Est du port",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 34,
    "name": "Elbtunnel-Bohrkopf (T.R.U.D.E. = Tief runter unter die Elbe)",
    "address": "22305 Hamburg-Nord, Germany",
    "category": "Architecture & photo",
    "detail": "Industriel / insolite / photo",
    "quarter": "Barmbek & City Nord",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/TRUDE-Schneidrad%20vor%20dem%20Museum%20der%20Arbeit%20in%20Hamburg-Barmbek-Nord%201.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:TRUDE-Schneidrad_vor_dem_Museum_der_Arbeit_in_Hamburg-Barmbek-Nord_1.jpg"
  },
  {
    "id": 35,
    "name": "Kulturflohmarkt Museum der Arbeit",
    "address": "Wiesendamm 3, 22305 Hamburg-Nord, Germany",
    "category": "Marchés",
    "detail": "Marché aux puces",
    "quarter": "Barmbek & City Nord",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Museum%20der%20Arbeit%20-%20Alte%20Fabrik.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Museum_der_Arbeit_-_Alte_Fabrik.jpg"
  },
  {
    "id": 36,
    "name": "Flohmarkt Flohschanze",
    "address": "Neuer Kamp 30, 20357 Altona, Germany",
    "category": "Marchés",
    "detail": "Marché aux puces",
    "quarter": "Schanze & Eimsbüttel",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 37,
    "name": "Reeperbahn",
    "address": "Reeperbahn, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / nightlife / photo",
    "quarter": "St. Pauli",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Reeperbahn,%20Hamburg%20(45387269632).jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Reeperbahn,_Hamburg_(45387269632).jpg"
  },
  {
    "id": 38,
    "name": "Heiligengeistfeld",
    "address": "Heiligengeistfeld 1, 20359 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Espace urbain / événement",
    "quarter": "St. Pauli",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Heiligengeistfeld%20Hamburg.220205.nnw.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Heiligengeistfeld_Hamburg.220205.nnw.jpg"
  },
  {
    "id": 39,
    "name": "Messe-Eingang Süd",
    "address": "20355 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Repère / salon",
    "quarter": "Centre",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 40,
    "name": "Ratsherrn Pilsener",
    "address": "Lagerstraße 30a, 20357 Altona, Germany",
    "category": "Manger & boire",
    "detail": "Brasserie / gastronomie",
    "quarter": "Schanze & Eimsbüttel",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Ratsherrn%20Brauerei.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Ratsherrn_Brauerei.jpg"
  },
  {
    "id": 41,
    "name": "Fischmarkt Hamburg Altona",
    "address": "Fischmarkt 2, 22767 Altona, Germany",
    "category": "Marchés",
    "detail": "Marché / gastronomie",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg-Altona-Altstadt%20Fischmarkt.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Hamburg-Altona-Altstadt_Fischmarkt.jpg"
  },
  {
    "id": 42,
    "name": "Altes Lotsenhaus",
    "address": "20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / port / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 43,
    "name": "Überseequartier",
    "address": "20457 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Architecture / quartier / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Westfield%20Hamburg%20%C3%9Cberseequartier.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Westfield_Hamburg_%C3%9Cberseequartier.jpg"
  },
  {
    "id": 44,
    "name": "Musical Boulevard Hamburg",
    "address": "Norderelbstraße 8, 20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / rive / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Musical%20Boulevard%20Hamburg.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Musical_Boulevard_Hamburg.jpg"
  },
  {
    "id": 45,
    "name": "Vieux tunnel sous l'Elbe",
    "address": "Bei den St. Pauli-Landungsbrücken, 20359 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / infrastructure / photo",
    "quarter": "St. Pauli",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Alter%20Elbtunel,%20Hamburg%20(15332211601).jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Alter_Elbtunel,_Hamburg_(15332211601).jpg"
  },
  {
    "id": 46,
    "name": "Hard Rock Cafe Hamburg",
    "address": "Bei den St. Pauli-Landungsbrücken 5, 20359 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Bar / restaurant",
    "quarter": "St. Pauli",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 47,
    "name": "Hamburg Hauptbahnhof",
    "address": "Hachmannplatz 16, 20099 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Gare / architecture / photo",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg%20Hauptbahnhof%20hall.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Hamburg_Hauptbahnhof_hall.jpg"
  },
  {
    "id": 48,
    "name": "Landzunge",
    "address": "Reginenstraße 13, 20539 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Vue / port / photo",
    "quarter": "Est du port",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 49,
    "name": "Elbbrücken",
    "address": "20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / station / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Elbbr%C3%BCcke%20U%20Bahn%20Bahnhof%20Hamburg%20B097.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Elbbr%C3%BCcke_U_Bahn_Bahnhof_Hamburg_B097.jpg"
  },
  {
    "id": 50,
    "name": "Elbbrücken",
    "address": "20539 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / station / photo",
    "quarter": "Est du port",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Elbbr%C3%BCcke%20U%20Bahn%20Bahnhof%20Hamburg%20B097.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Elbbr%C3%BCcke_U_Bahn_Bahnhof_Hamburg_B097.jpg"
  },
  {
    "id": 51,
    "name": "Lighthouse Zero",
    "address": "20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / art / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Lighthouse%20Zero,%20Hamburg.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Lighthouse_Zero,_Hamburg.jpg"
  },
  {
    "id": 52,
    "name": "Baakenhafen",
    "address": "20457 Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Baakenhafen%20im%20Hamburger%20Hafen.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Baakenhafen_im_Hamburger_Hafen.jpg"
  },
  {
    "id": 53,
    "name": "HafenCity",
    "address": "HafenCity, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Speicherstadt%20(Hamburg-HafenCity).1.hf.phb.ajb.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Speicherstadt_(Hamburg-HafenCity).1.hf.phb.ajb.jpg"
  },
  {
    "id": 54,
    "name": "Chilehaus",
    "address": "Chilehaus, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "Centre",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Chilehaus_(Hamburg-Altstadt).Blick_von_Osten.2.29132.ajb.jpg"
  },
  {
    "id": 55,
    "name": "Fleetschlösschen by Daniel Wischer",
    "address": "Brooktorkai 17, 20457 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Restaurant / architecture",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Fleetschl%C3%B6sschen.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Fleetschl%C3%B6sschen.jpg"
  },
  {
    "id": 56,
    "name": "Oberhafenbrücke",
    "address": "Oberhafenbrücke, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / pont / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Oberhafenbr%C3%BCcke%20(Hamburg-HafenCity).ajb.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Oberhafenbr%C3%BCcke_(Hamburg-HafenCity).ajb.jpg"
  },
  {
    "id": 57,
    "name": "Oberhafen-Kantine",
    "address": "Stockmeyerstraße 39, 20457 Hamburg, Germany",
    "category": "Manger & boire",
    "detail": "Gastronomie / architecture",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 58,
    "name": "Chilehaus",
    "address": "Fischertwiete 2A, 20095 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "Centre",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Chilehaus%20(Hamburg-Altstadt).Blick%20von%20Osten.2.29132.ajb.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Chilehaus_(Hamburg-Altstadt).Blick_von_Osten.2.29132.ajb.jpg"
  },
  {
    "id": 59,
    "name": "Speicherstadt",
    "address": "Speicherstadt, Hamburg, Germany",
    "category": "Ambiances & quartiers",
    "detail": "Quartier / architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Speicherstadt%20(Hamburg-HafenCity).1.hf.phb.ajb.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Speicherstadt_(Hamburg-HafenCity).1.hf.phb.ajb.jpg"
  },
  {
    "id": 60,
    "name": "Unilever Haus",
    "address": "Unilever Haus, Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg%20-%20Unilever%20Deutschland%20GmbH%20%26%20Marco%20Polo%20Tower.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Hamburg_-_Unilever_Deutschland_GmbH_%26_Marco_Polo_Tower.jpg"
  },
  {
    "id": 61,
    "name": "Marco Polo Tower",
    "address": "Am Strandkai 3, 20457 Hamburg, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Hamburg%20-%20Marco%20Polo%20Tower.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Hamburg_-_Marco_Polo_Tower.jpg"
  },
  {
    "id": 62,
    "name": "Dockland Office Building",
    "address": "Van-der-Smissen-Straße 9, 22767 Altona, Germany",
    "category": "Architecture & photo",
    "detail": "Architecture / photo",
    "quarter": "Altona & Fischmarkt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Dockland,%20Hamburg.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Dockland,_Hamburg.jpg"
  },
  {
    "id": 63,
    "name": "Elbphilharmonie Hamburg",
    "address": "Platz d. Deutschen Einheit 4, 20457 Hamburg, Germany",
    "category": "Culture & musées",
    "detail": "Architecture / culture / photo",
    "quarter": "HafenCity & Speicherstadt",
    "note": "",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Elbphilharmonie,%20Hamburg.jpg?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Elbphilharmonie,_Hamburg.jpg"
  },
  {
    "id": 64,
    "name": "PHOXXI - Temporäres Haus der Photographie",
    "address": "Deichtorstraße 1-2, 20095 Hamburg, Germany",
    "category": "Culture & musées",
    "detail": "Photographie / musée",
    "quarter": "Centre",
    "note": "",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 65,
    "name": "Hébergement — Lüneburger Str. 30",
    "address": "Lüneburger Str. 30, 21073 Hamburg, Germany",
    "category": "Hébergement",
    "detail": "Mon hébergement",
    "quarter": "Harburg",
    "note": "Adresse reconstruite à partir du nom du lieu; vérifier le point après import.",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  },
  {
    "id": 66,
    "name": "Indra Club",
    "address": "Große Freiheit 64, 22767 Hamburg, Germany",
    "category": "Culture & musées",
    "detail": "Club historique / Beatles / musique live",
    "quarter": "St. Pauli",
    "note": "Club historique où les Beatles se sont produits à leurs débuts.",
    "image": "https://commons.wikimedia.org/wiki/Special:FilePath/Indra-Club-Hamburg.png?width=1400",
    "imageCredit": "Wikimedia Commons",
    "imageKind": "photo",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Indra-Club-Hamburg.png"
  },
  {
    "id": 67,
    "name": "Bloomest Waschsalon Hamburg-Harburg",
    "address": "Harburger Ring 17, 21073 Hamburg, Germany",
    "category": "Adresses pratiques",
    "detail": "Laverie libre-service",
    "quarter": "Harburg",
    "note": "Adresse pratique à proximité du centre de Harburg.",
    "image": "",
    "imageCredit": "",
    "imageKind": "none",
    "imageSource": ""
  }
];
